export interface Country {
  code: string;
  name: string;
  phoneCode: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  // Africa (Reloadly supported countries)
  { code: 'DZ', name: 'Algeria', phoneCode: '+213', flag: '🇩🇿' },
  { code: 'AO', name: 'Angola', phoneCode: '+244', flag: '🇦🇴' },
  { code: 'BJ', name: 'Benin', phoneCode: '+229', flag: '🇧🇯' },
  { code: 'BW', name: 'Botswana', phoneCode: '+267', flag: '🇧🇼' },
  { code: 'BF', name: 'Burkina Faso', phoneCode: '+226', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', phoneCode: '+257', flag: '🇧🇮' },
  { code: 'CM', name: 'Cameroon', phoneCode: '+237', flag: '🇨🇲' },
  { code: 'CV', name: 'Cape Verde', phoneCode: '+238', flag: '🇨🇻' },
  { code: 'CF', name: 'Central African Republic', phoneCode: '+236', flag: '🇨🇫' },
  { code: 'TD', name: 'Chad', phoneCode: '+235', flag: '🇹🇩' },
  { code: 'KM', name: 'Comoros', phoneCode: '+269', flag: '🇰🇲' },
  { code: 'CG', name: 'Congo', phoneCode: '+242', flag: '🇨🇬' },
  { code: 'CD', name: 'Congo (Democratic Republic)', phoneCode: '+243', flag: '🇨🇩' },
  { code: 'CI', name: 'Côte d\'Ivoire', phoneCode: '+225', flag: '🇨🇮' },
  { code: 'DJ', name: 'Djibouti', phoneCode: '+253', flag: '🇩🇯' },
  { code: 'EG', name: 'Egypt', phoneCode: '+20', flag: '🇪🇬' },
  { code: 'GQ', name: 'Equatorial Guinea', phoneCode: '+240', flag: '🇬🇶' },
  { code: 'ER', name: 'Eritrea', phoneCode: '+291', flag: '🇪🇷' },
  { code: 'ET', name: 'Ethiopia', phoneCode: '+251', flag: '🇪🇹' },
  { code: 'GA', name: 'Gabon', phoneCode: '+241', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambia', phoneCode: '+220', flag: '🇬🇲' },
  { code: 'GH', name: 'Ghana', phoneCode: '+233', flag: '🇬🇭' },
  { code: 'GN', name: 'Guinea', phoneCode: '+224', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinea-Bissau', phoneCode: '+245', flag: '🇬🇼' },
  { code: 'KE', name: 'Kenya', phoneCode: '+254', flag: '🇰🇪' },
  { code: 'LS', name: 'Lesotho', phoneCode: '+266', flag: '🇱🇸' },
  { code: 'LR', name: 'Liberia', phoneCode: '+231', flag: '🇱🇷' },
  { code: 'LY', name: 'Libya', phoneCode: '+218', flag: '🇱🇾' },
  { code: 'MG', name: 'Madagascar', phoneCode: '+261', flag: '🇲🇬' },
  { code: 'MW', name: 'Malawi', phoneCode: '+265', flag: '🇲🇼' },
  { code: 'ML', name: 'Mali', phoneCode: '+223', flag: '🇲🇱' },
  { code: 'MR', name: 'Mauritania', phoneCode: '+222', flag: '🇲🇷' },
  { code: 'MU', name: 'Mauritius', phoneCode: '+230', flag: '🇲🇺' },
  { code: 'MA', name: 'Morocco', phoneCode: '+212', flag: '🇲🇦' },
  { code: 'MZ', name: 'Mozambique', phoneCode: '+258', flag: '🇲🇿' },
  { code: 'NA', name: 'Namibia', phoneCode: '+264', flag: '🇳🇦' },
  { code: 'NE', name: 'Niger', phoneCode: '+227', flag: '🇳🇪' },
  { code: 'NG', name: 'Nigeria', phoneCode: '+234', flag: '🇳🇬' },
  { code: 'RW', name: 'Rwanda', phoneCode: '+250', flag: '🇷🇼' },
  { code: 'ST', name: 'São Tomé and Príncipe', phoneCode: '+239', flag: '🇸🇹' },
  { code: 'SN', name: 'Senegal', phoneCode: '+221', flag: '🇸🇳' },
  { code: 'SC', name: 'Seychelles', phoneCode: '+248', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', phoneCode: '+232', flag: '🇸🇱' },
  { code: 'SO', name: 'Somalia', phoneCode: '+252', flag: '🇸🇴' },
  { code: 'ZA', name: 'South Africa', phoneCode: '+27', flag: '🇿🇦' },
  { code: 'SS', name: 'South Sudan', phoneCode: '+211', flag: '🇸🇸' },
  { code: 'SD', name: 'Sudan', phoneCode: '+249', flag: '🇸🇩' },
  { code: 'SZ', name: 'Swaziland', phoneCode: '+268', flag: '🇸🇿' },
  { code: 'TZ', name: 'Tanzania', phoneCode: '+255', flag: '🇹🇿' },
  { code: 'TG', name: 'Togo', phoneCode: '+228', flag: '🇹🇬' },
  { code: 'TN', name: 'Tunisia', phoneCode: '+216', flag: '🇹🇳' },
  { code: 'UG', name: 'Uganda', phoneCode: '+256', flag: '🇺🇬' },
  { code: 'ZM', name: 'Zambia', phoneCode: '+260', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', phoneCode: '+263', flag: '🇿🇼' },

  // Asia (Reloadly supported)
  { code: 'AF', name: 'Afghanistan', phoneCode: '+93', flag: '🇦🇫' },
  { code: 'BD', name: 'Bangladesh', phoneCode: '+880', flag: '🇧🇩' },
  { code: 'BT', name: 'Bhutan', phoneCode: '+975', flag: '🇧🇹' },
  { code: 'KH', name: 'Cambodia', phoneCode: '+855', flag: '🇰🇭' },
  { code: 'CN', name: 'China', phoneCode: '+86', flag: '🇨🇳' },
  { code: 'IN', name: 'India', phoneCode: '+91', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', phoneCode: '+62', flag: '🇮🇩' },
  { code: 'JP', name: 'Japan', phoneCode: '+81', flag: '🇯🇵' },
  { code: 'KZ', name: 'Kazakhstan', phoneCode: '+7', flag: '🇰🇿' },
  { code: 'KG', name: 'Kyrgyzstan', phoneCode: '+996', flag: '🇰🇬' },
  { code: 'LA', name: 'Laos', phoneCode: '+856', flag: '🇱🇦' },
  { code: 'MY', name: 'Malaysia', phoneCode: '+60', flag: '🇲🇾' },
  { code: 'MV', name: 'Maldives', phoneCode: '+960', flag: '🇲🇻' },
  { code: 'MN', name: 'Mongolia', phoneCode: '+976', flag: '🇲🇳' },
  { code: 'MM', name: 'Myanmar', phoneCode: '+95', flag: '🇲🇲' },
  { code: 'NP', name: 'Nepal', phoneCode: '+977', flag: '🇳🇵' },
  { code: 'KP', name: 'North Korea', phoneCode: '+850', flag: '🇰🇵' },
  { code: 'PK', name: 'Pakistan', phoneCode: '+92', flag: '🇵🇰' },
  { code: 'PH', name: 'Philippines', phoneCode: '+63', flag: '🇵🇭' },
  { code: 'SG', name: 'Singapore', phoneCode: '+65', flag: '🇸🇬' },
  { code: 'KR', name: 'South Korea', phoneCode: '+82', flag: '🇰🇷' },
  { code: 'LK', name: 'Sri Lanka', phoneCode: '+94', flag: '🇱🇰' },
  { code: 'TJ', name: 'Tajikistan', phoneCode: '+992', flag: '🇹🇯' },
  { code: 'TH', name: 'Thailand', phoneCode: '+66', flag: '🇹🇭' },
  { code: 'TL', name: 'Timor-Leste', phoneCode: '+670', flag: '🇹🇱' },
  { code: 'TM', name: 'Turkmenistan', phoneCode: '+993', flag: '🇹🇲' },
  { code: 'UZ', name: 'Uzbekistan', phoneCode: '+998', flag: '🇺🇿' },
  { code: 'VN', name: 'Vietnam', phoneCode: '+84', flag: '🇻🇳' },

  // Europe (Reloadly supported)
  { code: 'AL', name: 'Albania', phoneCode: '+355', flag: '🇦🇱' },
  { code: 'AD', name: 'Andorra', phoneCode: '+376', flag: '🇦🇩' },
  { code: 'AT', name: 'Austria', phoneCode: '+43', flag: '🇦🇹' },
  { code: 'BY', name: 'Belarus', phoneCode: '+375', flag: '🇧🇾' },
  { code: 'BE', name: 'Belgium', phoneCode: '+32', flag: '🇧🇪' },
  { code: 'BA', name: 'Bosnia and Herzegovina', phoneCode: '+387', flag: '🇧🇦' },
  { code: 'BG', name: 'Bulgaria', phoneCode: '+359', flag: '🇧🇬' },
  { code: 'HR', name: 'Croatia', phoneCode: '+385', flag: '🇭🇷' },
  { code: 'CY', name: 'Cyprus', phoneCode: '+357', flag: '🇨🇾' },
  { code: 'CZ', name: 'Czech Republic', phoneCode: '+420', flag: '🇨🇿' },
  { code: 'DK', name: 'Denmark', phoneCode: '+45', flag: '🇩🇰' },
  { code: 'EE', name: 'Estonia', phoneCode: '+372', flag: '🇪🇪' },
  { code: 'FI', name: 'Finland', phoneCode: '+358', flag: '🇫🇮' },
  { code: 'FR', name: 'France', phoneCode: '+33', flag: '🇫🇷' },
  { code: 'GE', name: 'Georgia', phoneCode: '+995', flag: '🇬🇪' },
  { code: 'DE', name: 'Germany', phoneCode: '+49', flag: '🇩🇪' },
  { code: 'GR', name: 'Greece', phoneCode: '+30', flag: '🇬🇷' },
  { code: 'HU', name: 'Hungary', phoneCode: '+36', flag: '🇭🇺' },
  { code: 'IS', name: 'Iceland', phoneCode: '+354', flag: '🇮🇸' },
  { code: 'IE', name: 'Ireland', phoneCode: '+353', flag: '🇮🇪' },
  { code: 'IT', name: 'Italy', phoneCode: '+39', flag: '🇮🇹' },
  { code: 'LV', name: 'Latvia', phoneCode: '+371', flag: '🇱🇻' },
  { code: 'LI', name: 'Liechtenstein', phoneCode: '+423', flag: '🇱🇮' },
  { code: 'LT', name: 'Lithuania', phoneCode: '+370', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', phoneCode: '+352', flag: '🇱🇺' },
  { code: 'MT', name: 'Malta', phoneCode: '+356', flag: '🇲🇹' },
  { code: 'MD', name: 'Moldova', phoneCode: '+373', flag: '🇲🇩' },
  { code: 'MC', name: 'Monaco', phoneCode: '+377', flag: '🇲🇨' },
  { code: 'ME', name: 'Montenegro', phoneCode: '+382', flag: '🇲🇪' },
  { code: 'NL', name: 'Netherlands', phoneCode: '+31', flag: '🇳🇱' },
  { code: 'MK', name: 'North Macedonia', phoneCode: '+389', flag: '🇲🇰' },
  { code: 'NO', name: 'Norway', phoneCode: '+47', flag: '🇳🇴' },
  { code: 'PL', name: 'Poland', phoneCode: '+48', flag: '🇵🇱' },
  { code: 'PT', name: 'Portugal', phoneCode: '+351', flag: '🇵🇹' },
  { code: 'RO', name: 'Romania', phoneCode: '+40', flag: '🇷🇴' },
  { code: 'RU', name: 'Russia', phoneCode: '+7', flag: '🇷🇺' },
  { code: 'SM', name: 'San Marino', phoneCode: '+378', flag: '🇸🇲' },
  { code: 'RS', name: 'Serbia', phoneCode: '+381', flag: '🇷🇸' },
  { code: 'SK', name: 'Slovakia', phoneCode: '+421', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenia', phoneCode: '+386', flag: '🇸🇮' },
  { code: 'ES', name: 'Spain', phoneCode: '+34', flag: '🇪🇸' },
  { code: 'SE', name: 'Sweden', phoneCode: '+46', flag: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', phoneCode: '+41', flag: '🇨🇭' },
  { code: 'TR', name: 'Turkey', phoneCode: '+90', flag: '🇹🇷' },
  { code: 'UA', name: 'Ukraine', phoneCode: '+380', flag: '🇺🇦' },
  { code: 'GB', name: 'United Kingdom', phoneCode: '+44', flag: '🇬🇧' },
  { code: 'VA', name: 'Vatican City', phoneCode: '+379', flag: '🇻🇦' },

  // Americas (Reloadly supported)
  { code: 'AR', name: 'Argentina', phoneCode: '+54', flag: '🇦🇷' },
  { code: 'BO', name: 'Bolivia', phoneCode: '+591', flag: '🇧🇴' },
  { code: 'BR', name: 'Brazil', phoneCode: '+55', flag: '🇧🇷' },
  { code: 'CA', name: 'Canada', phoneCode: '+1', flag: '🇨🇦' },
  { code: 'CL', name: 'Chile', phoneCode: '+56', flag: '🇨🇱' },
  { code: 'CO', name: 'Colombia', phoneCode: '+57', flag: '🇨🇴' },
  { code: 'CR', name: 'Costa Rica', phoneCode: '+506', flag: '🇨🇷' },
  { code: 'DO', name: 'Dominican Republic', phoneCode: '+1', flag: '🇩🇴' },
  { code: 'EC', name: 'Ecuador', phoneCode: '+593', flag: '🇪🇨' },
  { code: 'SV', name: 'El Salvador', phoneCode: '+503', flag: '🇸🇻' },
  { code: 'GT', name: 'Guatemala', phoneCode: '+502', flag: '🇬🇹' },
  { code: 'HT', name: 'Haiti', phoneCode: '+509', flag: '🇭🇹' },
  { code: 'HN', name: 'Honduras', phoneCode: '+504', flag: '🇭🇳' },
  { code: 'JM', name: 'Jamaica', phoneCode: '+1', flag: '🇯🇲' },
  { code: 'MX', name: 'Mexico', phoneCode: '+52', flag: '🇲🇽' },
  { code: 'NI', name: 'Nicaragua', phoneCode: '+505', flag: '🇳🇮' },
  { code: 'PA', name: 'Panama', phoneCode: '+507', flag: '🇵🇦' },
  { code: 'PY', name: 'Paraguay', phoneCode: '+595', flag: '🇵🇾' },
  { code: 'PE', name: 'Peru', phoneCode: '+51', flag: '🇵🇪' },
  { code: 'TT', name: 'Trinidad and Tobago', phoneCode: '+1', flag: '🇹🇹' },
  { code: 'US', name: 'United States', phoneCode: '+1', flag: '🇺🇸' },
  { code: 'UY', name: 'Uruguay', phoneCode: '+598', flag: '🇺🇾' },
  { code: 'VE', name: 'Venezuela', phoneCode: '+58', flag: '🇻🇪' },

  // Middle East (Reloadly supported)
  { code: 'BH', name: 'Bahrain', phoneCode: '+973', flag: '🇧🇭' },
  { code: 'IR', name: 'Iran', phoneCode: '+98', flag: '🇮🇷' },
  { code: 'IQ', name: 'Iraq', phoneCode: '+964', flag: '🇮🇶' },
  { code: 'IL', name: 'Israel', phoneCode: '+972', flag: '🇮🇱' },
  { code: 'JO', name: 'Jordan', phoneCode: '+962', flag: '🇯🇴' },
  { code: 'KW', name: 'Kuwait', phoneCode: '+965', flag: '🇰🇼' },
  { code: 'LB', name: 'Lebanon', phoneCode: '+961', flag: '🇱🇧' },
  { code: 'OM', name: 'Oman', phoneCode: '+968', flag: '🇴🇲' },
  { code: 'PS', name: 'Palestine', phoneCode: '+970', flag: '🇵🇸' },
  { code: 'QA', name: 'Qatar', phoneCode: '+974', flag: '🇶🇦' },
  { code: 'SA', name: 'Saudi Arabia', phoneCode: '+966', flag: '🇸🇦' },
  { code: 'SY', name: 'Syria', phoneCode: '+963', flag: '🇸🇾' },
  { code: 'AE', name: 'United Arab Emirates', phoneCode: '+971', flag: '🇦🇪' },
  { code: 'YE', name: 'Yemen', phoneCode: '+967', flag: '🇾🇪' },

  // Oceania (Reloadly supported)
  { code: 'AU', name: 'Australia', phoneCode: '+61', flag: '🇦🇺' },
  { code: 'FJ', name: 'Fiji', phoneCode: '+679', flag: '🇫🇯' },
  { code: 'NZ', name: 'New Zealand', phoneCode: '+64', flag: '🇳🇿' },
  { code: 'PG', name: 'Papua New Guinea', phoneCode: '+675', flag: '🇵🇬' },
  { code: 'WS', name: 'Samoa', phoneCode: '+685', flag: '🇼🇸' },
  { code: 'TO', name: 'Tonga', phoneCode: '+676', flag: '🇹🇴' },
  { code: 'VU', name: 'Vanuatu', phoneCode: '+678', flag: '🇻🇺' },
];

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(country => country.code === code);
}

export function getCountryByPhoneCode(phoneCode: string): Country | undefined {
  return COUNTRIES.find(country => country.phoneCode === phoneCode);
}

export function detectCountryFromIP(): Promise<string> {
  return fetch('https://ipapi.co/country_code/')
    .then(response => response.text())
    .then(countryCode => countryCode.toUpperCase())
    .catch(() => 'NG'); // Default to Nigeria if detection fails
}